version: '3.9'

services:

  db-aulas:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
    ports:
      - 3306:3306
    networks:
      - aulas

  adminer:
    image: adminer
    restart: always
    ports:
      - 5051:8080
    networks:
      - aulas

networks:
  aulas:
    driver: bridge